[package]
name = "sarissa"
version = "0.1.0"
edition = "2024"
description = "A fast, featureful full-text search library for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mosuka/sarissa"

[[bin]]
name = "sarissa"
path = "src/bin/sarissa.rs"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.98"
bincode = "1.3.3"
bit-vec = "0.8.0"
byteorder = "1.5.0"
chrono = { version = "0.4.41", features = ["serde"] }
clap = { version = "4.5.41", features = ["derive", "env", "color"] }
crc32fast = "1.5.0"
crossbeam-channel = "0.5.15"
crossbeam-deque = "0.8.6"
futures = "0.3.31"
lazy_static = "1.5.0"
memmap2 = "0.9.7"
num_cpus = "1.17.0"
parking_lot = "0.12.4"
rand = "0.9.2"
rayon = "1.10.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
unicode-segmentation = "1.12.0"
uuid = { version = "1.17.0", features = ["v4"] }
wide = "0.7.33"

[[bench]]
name = "bench"
harness = false

[dev-dependencies]
criterion = "0.6.0"
tempfile = "3.20.0"
tokio-test = "0.4.4"
